### PR TITLE
Change notPlayer to player for Russian roulette command

### PR DESCRIPTION
**Pull request by bullfrog0981**
For some reason notPlayer would use the current player that said no, this might just be for me but i'm going to propose this change anyhow

**Please describe the changes this PR makes and why it should be merged**:

**Semantic versioning classification:**  
- This PR changes the code in some way
  -  SEMVER patch (bug fix)
  - [ ] SEMVER minor (commands or args added)
  - [ ] SEMVER major (commands removed or renamed, args moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to the README.

### CODE REVIEW

**Comment by bullfrog0981** [comment]
Before fix:
Screen Shot 2019-12-10 at 10 23 03 AM

**Comment by dragonfire535** [comment]
Does playing a game against Xiao still work correctly if you do the same thing?

**Comment by dragonfire535** [comment]
Okay I figured out why this happens, 👍

**Comment by bullfrog0981** [comment]
ezpz bug fixing

**Pull request merged**
